name: Run

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Tag Name example
        run: |
          echo "::set-output name=proper::$(echo "${{  github.ref_name }}" | sed -r "s/-.*//")"
        id: proper

      # we will want to use @v1.2 because it has smarter error handling if a branch exists?    
      - uses: GuillaumeFalourd/create-other-repo-branch-action@v1
        with:
          repository_owner: ddymko
          repository_name: repo-b
          new_branch_name: ${{ steps.proper.outputs.proper }}
          access_token: ${{ secrets.API_TOKEN_GITHUB }}
      
      # there is an option to force push
      - name: Push repo-a to repo-b
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'data' 
          destination-github-username: 'ddymko'
          destination-repository-name: 'repo-b'
          user-email: ddymko@datawire.io
          target-branch: ${{ steps.proper.outputs.proper }}
          commit-message: ${{  github.ref_name }}
          
