name: Run

# {david} on releases 
# {david} grab tabs etc
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'chart/v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Tag Name example
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - uses: GuillaumeFalourd/create-other-repo-branch-action@v1.2
        with:
          repository_owner: ddymko
          repository_name: repo-b
          new_branch_name: ${{  github.ref_name }}
          access_token: ${{ secrets.API_TOKEN_GITHUB}}

      - name: Push repo-a to repo-b
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'data' # directory we want to push data from
          destination-github-username: 'ddymko' 
          destination-repository-name: 'repo-b'
          user-email: carles3@pina.cat
          target-branch: ${{  github.ref_name }}
          commit-message: ${{  github.ref_name }}