name: Run

on:
  push:
    tags:
      - "v*.*.*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  get-tagged-version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.proper.outputs.proper }}
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: GitHub Tag Name example
        run: |
          # For tags that have `-rc.N` we will strip this out in order create a "clean" branch `rel/vX.Y.Z`  
          echo "::set-output name=proper::$(echo "${{  github.ref_name }}" | sed -r "s/-.*//")"
        id: proper
        
  build:
    needs: [get-tagged-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: log
        shell: bash
        run: echo ${{ needs.get-version.outputs.PROPER }}
      - name: Create rel branch
        uses: GuillaumeFalourd/create-other-repo-branch-action@3f9f50c322fc03632d0909533ff350a210bc4a19
        with:
          repository_owner: "ddymko"
          ignore_branch_exists: true
          repository_name: "repo-b"
          new_branch_name: "rel/${{ needs.get-tagged-version.outputs.VERSION }}"
          ssh_deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
      ## there is an option to force push
      - name: Push repo-a to repo-b
        uses: cpina/github-action-push-to-another-repository@74596b72fae72d9b7b79e1b2992863c0f595c801
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "data"
          destination-github-username: "ddymko"
          destination-repository-name: "repo-b"
          user-email: ddymko@datawire.io
          target-branch: "rel/${{ needs.get-tagged-version.outputs.VERSION }}"
          commit-message: ${{  github.ref_name }}
          
